### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by jsatterlee** [hms-dbmi/pagoda2#43]
Hello,

I'm encountering the following error when attempting to install pagoda2:

```
**clang++ -std=gnu++11 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.4/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.4/Resources/library/RcppArmadillo/include" -I"/Library/Frameworks/R.framework/Versions/3.4/Resources/library/RcppProgress/include" -I/usr/local/include  -O3 -march=native -std=c++11 -pthread -fPIC -fopenmp -I"./include" -fPIC  -Wall -g -O2 -c base.cc -o base.o
clang: error: unsupported option '-fopenmp'
make[1]: *** [base.o] Error 1
make: *** [sublibraries] Error 1
ERROR: compilation failed for package ‘pagoda2’
removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/pagoda2’
Installation failed: Command failed (1)**

```
I've made sure that clang4, gfortran, etc. are installed. I also updated my ~/.R/Makevars:

```
CC=/usr/local/clang4/bin/clang
CXX=/usr/local/clang4/bin/clang++
CXX11=/usr/local/clang4/bin/clang++
CXX14=/usr/local/clang4/bin/clang++
CXX17=/usr/local/clang4/bin/clang++
CXX1X=/usr/local/clang4/bin/clang++
LDFLAGS=-L/usr/local/clang4/lib


```
For what it's worth, it appears that the installer uses the -fopenmp argument without generating an error in the previous line of output:
```
> /usr/local/clang4/bin/clang++ -std=gnu++11 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.4/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.4/Resources/library/RcppArmadillo/include" -I"/Library/Frameworks/R.framework/Versions/3.4/Resources/library/RcppProgress/include" -I/usr/local/include  -I"../inst/include" -I"./n2/include" -I"./include" -fopenmp  -fPIC  -Wall -g -O2 -c rank.cpp -o rank.o
```

Any help would be greatly appreciated!
-Jack

**Comment by VPetukhov** [comment]
Thanks for the solution! Did you try to set these variables in your user's Makevars (`~/.R/Makevars`)? It should be a proper way to do that. If it doesn't work, perhaps pagoda changes your default setting, and we need to fix it.

**Comment by jsatterlee** [comment]
Hi Viktor,

Yes I defined those variables in ~/.R/Makevars but it didn’t resolve the error. I think you’re right — the settings must be getting changed at some point during installation. 

Thanks,
Jack

**Comment by nicolafattorelli** [comment]
Hello,

I was encountering the same error while installing pagoda2, but Jack's solution didn't work for me.
Then we noticed that in the last step of pagoda2 installation, the settings somehow changed and the Apple version of clang was used (mine was Apple LLVM version 9.1.0 (clang-902.0.37.1)) instead of clang4 that I had installed following [these instructions](http://thecoatlessprofessor.com/programming/openmp-in-r-on-os-x/#after-3-4-0).

Looking into the Apple clang directory (which for me is /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin), we saw that clang++ was not symlinked to the newly installed clang4, but indeed to the pre-included version.

What worked for me was just to remove clang++ and create a symlink to clang4:

```
rm clang++
ln -s /usr/local/clang4/bin/clang++ clang++
```

Then I was able to install pagoda2 correctly.

Best,
Nicola

**Comment by DRLaks** [comment]
Is anyone at pagoda 2 going to resolve this issue? I can't seem to get the program installed either and I receive the error:
clang: error: unsupported option '-fopenmp'
I use a MacOs High Sierra 10.13.3

**Comment by VPetukhov** [comment]
Did you try the solution with clang4?

**Comment by DRLaks** [comment]
Hello Viktor, I installed clang 4 initially.

**Comment by VPetukhov** [comment]
Dan,
I meant not only installation, but also setting it as the default compiler. Either changing your system preferences or changing Makevars as was suggested in the [comment](https://github.com/hms-dbmi/pagoda2/issues/53#issuecomment-407098416).
